---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/
patches:
  - ./patches/microservice/sample1/deployment.yaml
  - ./patches/microservice/sample2/deployment.yaml
