apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./microservice/sample1/deployment.yaml
- ./microservice/sample1/service.yaml
- ./microservice/sample2/deployment.yaml
- ./microservice/sample2/service.yaml
images:
- name: sample1-image
  newName: deepakjotwani/sample1
  newTag: "6227139"
- name: sample2-image
