apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./microservice/sample1/deployment.yaml
- ./microservice/sample1/service.yaml
- ./microservice/sample2/deployment.yaml
- ./microservice/sample2/service.yaml
images:
- name: sample1-image
  newName: deepakjotwani/sample1
  newTag: 217d9fe
- name: sample2-image
  newName: deepakjotwani/sample2
  newTag: f16c679
