---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample1-deployment
spec:
  selector:
    matchLabels:
      app: sample1
  replicas: 2
  template:
    spec:
      containers:
        - name: sample1
