---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample2-deployment
spec:
  selector:
    matchLabels:
      app: sample2
  template:
    metadata:
      labels:
        app: sample2
    spec:
      containers:
        - name: sample2
          image: sample2-image   # overridden by kustomize
