---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample1-deployment
spec:
  selector:
    matchLabels:
      app: sample1
  template:
    metadata:
      labels:
        app: sample1
    spec:
      containers:
        - name: sample1
          image: sample1-image   # overridden by kustomize
