name: lint

on:
  push:
    branches:
      - "master"

jobs:
  delint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_KUBERNETES_KUBEVAL: true
          VALIDATE_YAML: true
          YAML_CONFIG_FILE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
