---
name: Receive latest tag on repository_dispatch
on:
  repository_dispatch:
jobs:
  receive-tag:
    if: github.event.action == 'update_tag_docker'
    runs-on: ubuntu-latest
    steps:
      - name: Validating the input
        run: |
          if [[ ${{ github.event.client_payload.latestTag }} =~ ^[0-9a-f]{7,40}$ && ${{ github.event.client_payload.microserviceImage }} =~ ^[a-zA-Z0-9-]+$ && ${{ github.event.client_payload.imageName }} =~ ^[0-9A-Za-z/\s-\s.]+$ ]]; then
          echo "Inputs received are valid"
          else
          echo "Inputs received are invalid"
          exit 1
          fi

      - name: Running Docker image
        run: | 
          docker login -u deepakjotwani -p ${{ secrets.DOCKER_PASSWORD }}
          docker run deepakjotwani/kustomize:latest ${{ secrets.ACCESS_TOKEN }} ${{ github.event.client_payload.microserviceImage }} ${{ github.event.client_payload.imageName }} ${{ github.event.client_payload.latestTag }} "$GPG_PRIVATE_KEY"
        env:
          GPG_PRIVATE_KEY : ${{secrets.GPG_PRIVATE_KEY}}

      - name: Creating a PR
        run: hub pull-request -m "feat:Updating tag for ${{ github.event.client_payload.microserviceImage }}" -b master -h feature/Updating-${{ github.event.client_payload.microserviceImage }}-tag-${{ github.event.client_payload.latestTag }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}          
