---
name: Receive latest tag on repository_dispatch
on:
  repository_dispatch:
    branches: [master]
jobs:
  receive-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Kustomize
        run: |
          cd /tmp
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

      - name: Updating the TAG for sample1
        if: github.event.action == 'sample1'
        run: |
          cd Services/base
          kustomize edit set image sample1-image=deepakjotwani/sample1:${{ github.event.client_payload.sample1_latestTag }}

      - name: Updating the TAG for sample2
        if: github.event.action == 'sample2'
        run: |
          cd Services/base
          kustomize edit set image sample2-image=deepakjotwani/sample2:${{ github.event.client_payload.sample2_latestTag }}
  
      - name: Creation of feature Branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"        
          git checkout -b feature/Updating-${{ github.event.action }}
          git commit -am "Updating tag for '${{ github.event.action }}'"
          git push origin
