---
name: Receive latest tag on repository_dispatch
on:
  repository_dispatch:
    branches: [master]
jobs:
  receive-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

      - name: Updating the TAG for sample1
        if: github.event.action == 'sample1_latestTag'
        run: |
          cd Services/base
          kustomize edit set image sample1-image=deepakjotwani/sample1:${{ github.event.client_payload.sample1_latestTag }}

      - name: Updating the TAG for sample2
        if: github.event.action == 'sample2_latestTag'
        run: |
          cd Services/base
          kustomize edit set image sample2-image=deepakjotwani/sample2:${{ github.event.client_payload.sample2_latestTag }}  

      - name: Remove Kustomize
        run: rm kustomize

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump docker tag"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
