---
name: Receive latest tag on repository_dispatch
on:
  repository_dispatch:
jobs:
  receive-tag:
    if: github.event.action == 'update_tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Creating Feature Branch
        run: | 
          git config --global user.email "${{ github.event.client_payload.commitEmail }}"
          git config --global user.name "${{ github.event.client_payload.commitUserName }}"
          git checkout -b feature/Updating-${{ github.event.client_payload.microserviceImage }}-tag-${{ github.event.client_payload.latestTag }}

      - name: Setup Kustomize
        run: |
          cd /tmp
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

      - name: Updating the TAG
        run: |
          cd Services/base
          kustomize edit set image ${{ github.event.client_payload.microserviceImage }}=${{ github.event.client_payload.imageName }}:${{ github.event.client_payload.latestTag }}
  
      - name: Commiting changes to feature branch
        run: |
          export FEATURE_SHA=$(curl https://api.github.com/repos/deepakjotwani/receiver/git/ref/heads/feature/Updating-${{ github.event.client_payload.microserviceImage }}-tag-${{ github.event.client_payload.latestTag }} -u ${{ secrets.ACCESS_TOKEN }} | jq -r '.object.sha')
          export TREE_SHA=$(curl  https://api.github.com/repos/deepakjotwani/receiver/git/commits/$FEATURE_SHA -u ${{ secrets.ACCESS_TOKEN }} | jq -r '.tree.sha')
          curl -X POST https://api.github.com/repos/deepakjotwani/receiver/git/commits \
          -H 'Accept: application/json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"message": "Updating tag for ${{ github.event.client_payload.microserviceImage }}","committer": {"name": "${{ github.event.client_payload.commitUserName }}", "email": "${{ github.event.client_payload.commitEmail }}"}, "parents": [] ,"tree": "'"$TREE_SHA"'"}'

      - name: Pushing changes to feature branch
        run: |       
          git push origin feature/Updating-${{ github.event.client_payload.microserviceImage }}-tag-${{ github.event.client_payload.latestTag }}          

      - name: Creating a PR
        run: hub pull-request -m "feat:Updating tag for ${{ github.event.client_payload.microserviceImage }}" -b master -h feature/Updating-${{ github.event.client_payload.microserviceImage }}-tag-${{ github.event.client_payload.latestTag }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
