---
name: Receive latest tag on repository_dispatch
on:
  repository_dispatch:
jobs:
  receive-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Creating Feature Branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"        
          git checkout -b feature/Updating-${{ github.event.action }}-tag-${{ github.event.client_payload.latestTag }}

      - name: Setup Kustomize
        run: |
          cd /tmp
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

      - name: Updating the TAG
        run: |
          cd Services/base
          kustomize edit set image ${{ github.event.client_payload.microserviceImage }}=${{ github.event.client_payload.imageName }}:${{ github.event.client_payload.latestTag }}
  
      - name: Pushing changes to feature branch
        run: |       
          git commit -am "Updating tag for '${{ github.event.action }}'"
          git push origin feature/Updating-${{ github.event.action }}-tag-${{ github.event.client_payload.latestTag }}

      - name: Creating a PR
        run: hub pull-request -m "feat:Updating tag for ${{ github.event.action }}" -b master -h feature/Updating-${{ github.event.action }}-tag-${{ github.event.client_payload.latestTag }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
