---
name: Receive latest tag on repository_dispatch
on:
  repository_dispatch:
jobs:
  receive-tag:
    if: github.event.action == 'update_tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validating the input
        run: |
          if [[ ${{ github.event.client_payload.latestTag }} =~ ^[0-9a-f]{7,40}$ && ${{ github.event.client_payload.microserviceImage }} =~ ^[a-zA-Z0-9-]+$ && ${{ github.event.client_payload.imageName }} =~ [0-9A-Za-z/\s-\s.] ]]; then
          echo "Inputs are valid"
          else
          exit 1
          fi

      # - name: Creating Feature Branch
      #   run: | 
      #     git config --global user.email "dpkjotwani12@gmail.com"
      #     git config --global user.name "deepakjotwani"
      #     git checkout -b feature/Updating-${{ github.event.client_payload.microserviceImage }}-tag-${{ github.event.client_payload.latestTag }}

      # - name: Setup Kustomize
      #   run: |
      #     cd /tmp
      #     curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

      # - name: Updating the TAG
      #   run: |
      #     cd Services/base
      #     kustomize edit set image ${{ github.event.client_payload.microserviceImage }}=${{ github.event.client_payload.imageName }}:${{ github.event.client_payload.latestTag }}

      # - name: Importing the key
      #   run: |
      #     echo $GPG_PRIVATE_KEY | tr ',' '\n' > /tmp/private_key.gpg
      #     gpg --import /tmp/private_key.gpg
      #   shell: bash
      #   env:
      #     GPG_PRIVATE_KEY : ${{secrets.GPG_PRIVATE_KEY}}

      # - name: Commiting & Pushing changes to feature branch
      #   run: |
      #     git commit -S -am "Updating tag for ${{ github.event.client_payload.microserviceImage }}"
      #     git push origin feature/Updating-${{ github.event.client_payload.microserviceImage }}-tag-${{ github.event.client_payload.latestTag }}          

      # - name: Creating a PR
      #   run: hub pull-request -m "feat:Updating tag for ${{ github.event.client_payload.microserviceImage }}" -b master -h feature/Updating-${{ github.event.client_payload.microserviceImage }}-tag-${{ github.event.client_payload.latestTag }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # - name: Removing the key
      #   run: rm /tmp/private_key.gpg